#ifndef ROADCONSTS_H_INCLUDED
#define ROADCONSTS_H_INCLUDED

enum enumRoads
{
    ROAD_NONE = -1,

    // List in order of place ID
    ROAD_ERICENNES_CHORAS = 0,
    ROAD_ERICENNES_KETH_KETHER = 1,
    ROAD_ERICENNES_KETH_ENTWEIR = 2,

    ROAD_KETH_KETHER_KETH_ENTWEIR = 3,
    ROAD_KETH_KETHER_VIELLEICHT = 4,
    ROAD_KETH_KETHER_QUELLUDE = 5,

    ROAD_KETH_ENTWEIR_AMBLEFORTH = 6,

    ROAD_VIELLEICHT_QUELLUDE = 7

};
const unsigned ROAD_MARKER_FIRST = ROAD_ERICENNES_CHORAS;
const unsigned ROAD_MARKER_LAST = ROAD_VIELLEICHT_QUELLUDE;

#endif // ROADCONSTS_H_INCLUDED
